jdbc:
  database:
    jdbcUrl: jdbc:mysql://localhost:13306/database
    username: user
    password: password

jetty:
  connectors:
    - port: 9090

metrics:
  reporters:
    - type: slf4j
      period: 5s