jdbc:
  database:
    jdbcUrl: jdbc:mysql://database:3306/database
    username: user
    password: password

metrics:
  reporters:
    - type: slf4j
      period: 5s

log:
  level: info
  loggers:
    io.bootique.jetty.server.RequestLogger:
      level: warn
